//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorAgent.WebService {
    using System.Runtime.Serialization;
    using System;
    using Rlc.Monitor;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MonitorAgent.WebService.ChatMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MonitorAgent.WebService.ThumbsizeMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MonitorAgent.WebService.PollIntervalMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MonitorAgent.WebService.PollModeMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MonitorAgent.WebService.ImageDataMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MonitorAgent.WebService.RegisterMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MonitorAgent.WebService.EmptyMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MonitorAgent.WebService.DirectoryCommandMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MonitorAgent.WebService.FileDataMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MonitorAgent.WebService.DirectoryDataMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MonitorAgent.WebService.ImageNoChangeMessage))]
    public partial class BaseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid AgentIdField;
        
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid AgentId {
            get {
                return this.AgentIdField;
            }
            set {
                if ((this.AgentIdField.Equals(value) != true)) {
                    this.AgentIdField = value;
                    this.RaisePropertyChanged("AgentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ChatMessage : MonitorAgent.WebService.BaseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThumbsizeMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ThumbsizeMessage : MonitorAgent.WebService.BaseMessage {
        
        private int WidthField;
        
        private int HeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PollIntervalMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PollIntervalMessage : MonitorAgent.WebService.BaseMessage {
        private AgentData agentData;
        private int IntervalInMillisecondsField;
        private int v;

        public PollIntervalMessage(AgentData agentData, int v)
        {
            this.agentData = agentData;
            this.v = v;
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IntervalInMilliseconds {
            get {
                return this.IntervalInMillisecondsField;
            }
            set {
                if ((this.IntervalInMillisecondsField.Equals(value) != true)) {
                    this.IntervalInMillisecondsField = value;
                    this.RaisePropertyChanged("IntervalInMilliseconds");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PollModeMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PollModeMessage : MonitorAgent.WebService.BaseMessage {
        
        private MonitorAgent.WebService.PollModeOptions PollModeField;

        public static object PollModeOptions { get; set; }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public MonitorAgent.WebService.PollModeOptions PollMode {
            get {
                return this.PollModeField;
            }
            set {
                if ((this.PollModeField.Equals(value) != true)) {
                    this.PollModeField = value;
                    this.RaisePropertyChanged("PollMode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageDataMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ImageDataMessage : MonitorAgent.WebService.BaseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageDataField;
        
        private bool IsThumbnailField;
        
        private bool IsPartialField;
        
        private int XField;
        
        private int YField;
        
        private int FullWidthField;
        
        private int FullHeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsThumbnail {
            get {
                return this.IsThumbnailField;
            }
            set {
                if ((this.IsThumbnailField.Equals(value) != true)) {
                    this.IsThumbnailField = value;
                    this.RaisePropertyChanged("IsThumbnail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool IsPartial {
            get {
                return this.IsPartialField;
            }
            set {
                if ((this.IsPartialField.Equals(value) != true)) {
                    this.IsPartialField = value;
                    this.RaisePropertyChanged("IsPartial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int FullWidth {
            get {
                return this.FullWidthField;
            }
            set {
                if ((this.FullWidthField.Equals(value) != true)) {
                    this.FullWidthField = value;
                    this.RaisePropertyChanged("FullWidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int FullHeight {
            get {
                return this.FullHeightField;
            }
            set {
                if ((this.FullHeightField.Equals(value) != true)) {
                    this.FullHeightField = value;
                    this.RaisePropertyChanged("FullHeight");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RegisterMessage : MonitorAgent.WebService.BaseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComputerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ComputerName {
            get {
                return this.ComputerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ComputerNameField, value) != true)) {
                    this.ComputerNameField = value;
                    this.RaisePropertyChanged("ComputerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserInfo {
            get {
                return this.UserInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserInfoField, value) != true)) {
                    this.UserInfoField = value;
                    this.RaisePropertyChanged("UserInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmptyMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EmptyMessage : MonitorAgent.WebService.BaseMessage {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectoryCommandMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DirectoryCommandMessage : MonitorAgent.WebService.BaseMessage {
        
        private MonitorAgent.WebService.Action CommandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentDirectoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MonitorAgent.WebService.ArrayOfString ContentToFetchField;
        private AgentData agentData;

        public DirectoryCommandMessage(AgentData agentData)
        {
            this.agentData = agentData;
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public MonitorAgent.WebService.Action Command {
            get {
                return this.CommandField;
            }
            set {
                if ((this.CommandField.Equals(value) != true)) {
                    this.CommandField = value;
                    this.RaisePropertyChanged("Command");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CurrentDirectory {
            get {
                return this.CurrentDirectoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentDirectoryField, value) != true)) {
                    this.CurrentDirectoryField = value;
                    this.RaisePropertyChanged("CurrentDirectory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MonitorAgent.WebService.ArrayOfString ContentToFetch {
            get {
                return this.ContentToFetchField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentToFetchField, value) != true)) {
                    this.ContentToFetchField = value;
                    this.RaisePropertyChanged("ContentToFetch");
                }
            }
        }

        public static object Action { get; set; }

        public static implicit operator DirectoryCommandMessage(DirectoryCommandMessage v)
        {
            throw new NotImplementedException();
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileDataMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FileDataMessage : MonitorAgent.WebService.BaseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] FileData {
            get {
                return this.FileDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FileDataField, value) != true)) {
                    this.FileDataField = value;
                    this.RaisePropertyChanged("FileData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectoryDataMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DirectoryDataMessage : MonitorAgent.WebService.BaseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentFolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MonitorAgent.WebService.ArrayOfString FoldersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MonitorAgent.WebService.ArrayOfString FilesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CurrentFolder {
            get {
                return this.CurrentFolderField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentFolderField, value) != true)) {
                    this.CurrentFolderField = value;
                    this.RaisePropertyChanged("CurrentFolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MonitorAgent.WebService.ArrayOfString Folders {
            get {
                return this.FoldersField;
            }
            set {
                if ((object.ReferenceEquals(this.FoldersField, value) != true)) {
                    this.FoldersField = value;
                    this.RaisePropertyChanged("Folders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MonitorAgent.WebService.ArrayOfString Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageNoChangeMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ImageNoChangeMessage : MonitorAgent.WebService.BaseMessage {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PollModeOptions", Namespace="http://tempuri.org/")]
    public enum PollModeOptions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Register = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PollForCommands = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PostThumbnail = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PostFullsize = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Action", Namespace="http://tempuri.org/")]
    public enum Action : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FetchCurrentData = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangeDirectory = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FetchContent = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CopyContent = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.CommandHandlerSoap")]
    public interface CommandHandlerSoap {
        
        // CODEGEN: Generating message contract since element name message from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Poll", ReplyAction="*")]
        MonitorAgent.WebService.PollResponse Poll(MonitorAgent.WebService.PollRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PollRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Poll", Namespace="http://tempuri.org/", Order=0)]
        public MonitorAgent.WebService.PollRequestBody Body;
        
        public PollRequest() {
        }
        
        public PollRequest(MonitorAgent.WebService.PollRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PollRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MonitorAgent.WebService.BaseMessage message;
        
        public PollRequestBody() {
        }
        
        public PollRequestBody(MonitorAgent.WebService.BaseMessage message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PollResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PollResponse", Namespace="http://tempuri.org/", Order=0)]
        public MonitorAgent.WebService.PollResponseBody Body;
        
        public PollResponse() {
        }
        
        public PollResponse(MonitorAgent.WebService.PollResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PollResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MonitorAgent.WebService.BaseMessage[] PollResult;
        
        public PollResponseBody() {
        }
        
        public PollResponseBody(MonitorAgent.WebService.BaseMessage[] PollResult) {
            this.PollResult = PollResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommandHandlerSoapChannel : MonitorAgent.WebService.CommandHandlerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommandHandlerSoapClient : System.ServiceModel.ClientBase<MonitorAgent.WebService.CommandHandlerSoap>, MonitorAgent.WebService.CommandHandlerSoap {
        
        public CommandHandlerSoapClient() {
        }
        
        public CommandHandlerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommandHandlerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandHandlerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandHandlerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MonitorAgent.WebService.PollResponse MonitorAgent.WebService.CommandHandlerSoap.Poll(MonitorAgent.WebService.PollRequest request) {
            return base.Channel.Poll(request);
        }
        
        public MonitorAgent.WebService.BaseMessage[] Poll(MonitorAgent.WebService.BaseMessage message) {
            MonitorAgent.WebService.PollRequest inValue = new MonitorAgent.WebService.PollRequest();
            inValue.Body = new MonitorAgent.WebService.PollRequestBody();
            inValue.Body.message = message;
            MonitorAgent.WebService.PollResponse retVal = ((MonitorAgent.WebService.CommandHandlerSoap)(this)).Poll(inValue);
            return retVal.Body.PollResult;
        }
    }
}
